CREATE TABLE IF NOT EXISTS ACTORS (
  ACTOR_ID BIGINT PRIMARY KEY,
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(20),
  BIRTHDATE VARCHAR(15)
);
CREATE TABLE IF NOT EXISTS CINEMACOMPANY (
  COMPANY_ID VARCHAR(36) PRIMARY KEY,
  COMPANY_NAME VARCHAR(40)
);
CREATE TABLE IF NOT EXISTS STYLES (
  STYLE_ID VARCHAR(36) PRIMARY KEY,
  STYLE_NAME VARCHAR(20),
  COUNTRY_NAME VARCHAR(15)
);
CREATE TABLE IF NOT EXISTS FILMS (
  FILM_ID VARCHAR(36) PRIMARY KEY,
  FILM_NAME VARCHAR(25),
  RELESE_DATE VARCHAR(15),
  STYLE VARCHAR(20),
  COMPANY VARCHAR(36)
);